name: RemoteListener
options:
  bundleIdPrefix: com.rl
  deploymentTarget:
    iOS: "16.0"
  xcodeVersion: "15.0"
  projectFormat: "1.18"
  generateEmptyDirectories: true

packages:
  RLKit:
    path: ./RLKit
  CryptoSwift:
    url: https://github.com/krzyzanowskim/CryptoSwift
    from: "1.8.0"

targets:
  RemoteListener:
    type: application
    platform: iOS
    sources:
      - RemoteListener
    dependencies:
      - package: RLKit
      - package: CryptoSwift
    settings:
      base:
        INFOPLIST_KEY_UIApplicationSceneManifest_Generation: true
        INFOPLIST_KEY_UIApplicationSupportsIndirectInputEvents: true
        INFOPLIST_KEY_UILaunchScreen_Generation: true
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPad: "UIInterfaceOrientationPortrait UIInterfaceOrientationPortraitUpsideDown UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        INFOPLIST_KEY_UISupportedInterfaceOrientations_iPhone: "UIInterfaceOrientationPortrait UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight"
        MARKETING_VERSION: "1.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_EMIT_LOC_STRINGS: "YES"
        ASSETCATALOG_COMPILER_APPICON_NAME: AppIcon
        ASSETCATALOG_COMPILER_GLOBAL_ACCENT_COLOR_NAME: AccentColor
        SWIFT_VERSION: "5.0"
        CODE_SIGN_IDENTITY: "Apple Development"
    entitlements:
      path: RemoteListener/RemoteListener.entitlements
      properties:
        com.apple.security.network.client: true
